### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KiExitDispatcher** [hackirby/skuld#16]
could i update the antidbg? and add some features to the antidbg

**Comment by hackirby** [comment]
Feel free to submit a pull request with any useful changes or fixes; I'll gladly review it and (maybe) accept it. If your contributions focus on enhancing the project without personal gain, your pull requests will be appreciated.

**Comment by KiExitDispatcher** [comment]
aight, gotchu. ill implement the simpler antidbg which is on my profile that lowered detection rate, the other versions on it are yk. for products like hiding threads from debugger which can be still be bypassed but, i dont plan adding like check isremdeb present or is deb present to the simpler one ill fork rn and start working on it.

**Comment by KiExitDispatcher** [comment]
- Blocks over 50+ popular debugging software.
- Blocks IsDebuggerPresent.
- Prevents debuggers and traffic debuggers.
- Detects and kills blacklisted processes.
- Detects windows associated with debugging tools.
- Checks system uptime and running processes.
- Checks disk size, RAM, and number of processors.
- Verifies GPU information.
- Performs IP check against a blacklist.
- Lowers VirusTotal detection to 2/72.

if you want to check it out : https://github.com/EvilBytecode/Anti-Debug
it can be usefull if you will ever sell your product. anyways ill do PR.

**Comment by hackirby** [comment]
I merged your pull request. Checking window names to close processes is an excellent approach. Much appreciated!

**Comment by KiExitDispatcher** [comment]
tysm 👍
