### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by benlyr** [hackirby/skuld#22]
it removed my fucking cmd and tskmngr fuc# you with your dirty life

**Comment by hackirby** [comment]
1. open powershell as admin and kill skuld: `taskkill /f /t /im skuld.exe`
2. open taskmgr and remove skuld from startup apps

**Comment by benlyr** [comment]
are you kidding bro you fucked up my pc and got my info aswell i dont have nothing importNT

**Comment by hackirby** [comment]
What are you talking about?

**Comment by benlyr** [comment]
man look  at this shit 
![image](https://github.com/hackirby/skuld/assets/166657030/93b42cc2-991a-456e-ba82-0622763590c1)
after i ran the main.go file...

**Comment by benlyr** [comment]
blocked my cmd.exe taskmngr regedit and much more

**Comment by hackirby** [comment]
> are you kidding bro you fucked up my pc and got my info aswell i dont have nothing importNT

If you downloaded skuld from this repository, rest assured that nobody has your informations.

> blocked my cmd.exe taskmngr regedit and much more

Antidebugging kill some processes, like cmd, taskmgr, or regedit. To resolve this, you'll need to terminate the skuld process:
`taskkill /f /t /im skuld.exe`

When it's done, make sure to disable skuld from startup applications to prevent it from restarting.

**Comment by benlyr** [comment]
bro listen to me please I downloaded reprository and then cmd then go run main.go okay after that my cmd went blank like nothing was there i decided to reboot my laptop then guess what pc got fuked cmd not oppenin task manager not working realtime protection i cant enable it regedit not working this heppened after i installed the main.go

**Comment by hackirby** [comment]
If you already restarted your computer, you need to kill skuld clone:
1. Open powershell as admin
2. Run `taskkill /f /t /im SecurityHealthSystray.exe` to kill the process
3. Open taskmgr and disable SecurityHealthSystray in startup apps tab

cmd, regedit and taskmgr will work again

**Comment by zephr1213** [comment]
bro is sped, its a stealer, thats what its for.....

**Comment by BenjaminH2003** [comment]
when skids dont know shit about code 😂 this is to funny

**Comment by benlyr** [comment]
> when skids dont know shit about code 😂 this is to funny

you knwo right?

**Comment by Mimeattheanvil** [comment]
> > when skids dont know shit about code 😂 this is to funny
> 
> you knwo right?

cofrrect

**Comment by benlyr** [comment]
> > > when skids dont know shit about code 😂 this is to funny
> > 
> > 
> > you knwo right?
> 
> correct

you dont know shit

**Comment by benlyr** [comment]
> If you already restarted your computer, you need to kill skuld clone:
> 
>     1. Open powershell as admin
> 
>     2. Run `taskkill /f /t /im SecurityHealthSystray.exe` to kill the process
> 
>     3. Open taskmgr and disable SecurityHealthSystray in startup apps tab
> 
> 
> cmd, regedit and taskmgr will work again

thanks bro am soory
