### ISSUE TITLE
doesnt do anything

### ISSUE THREAD

**Issue by mahdi13377** [hackirby/skuld#26]
webhook correct i compiled ran it nothing happened ran in console didnt print any logs or error n i tried without any flags and it still just does nothing

**Comment by mahdi13377** [comment]
nevermind it works without the hide console flag so thats weird

**Comment by hackirby** [comment]
Hey, I discovered that it's due to the `program.IsAlreadyRunning()` function.

I modified installation instructions: https://github.com/hackirby/skuld/commit/d0ec8c9715c5c79029d55aed440cd6346adcd0d4

Thank's a lot for reporting this error !
