### ISSUE TITLE
🤦 

### ISSUE THREAD

**Issue by imvast** [hackirby/skuld#3]
- 0 credits to original codes
- legit copy and paste most of the files - "built on top of" - synonym for skidding

**Comment by imvast** [comment]
+ removed all reference of original and said "made by kirby"
- top tier extra chromosome

**Comment by hackirby** [comment]
Dear vast,

Skuld was indeed influenced by various sources, drawing inspiration from different individuals and their work in the field. It is common practice within the coding community to build upon existing knowledge and resources. Every stealer reuses code from others stealers, themselves reusing code from others stealers, etc... I would like to emphasize that while I utilized certain tools, such as https://github.com/moonD4rk/HackBrowserData, for browser data decryption, all the coding work related to Skuld was done by me.

In the README file of the project, due credit has been given to the aforementioned GitHub repository.

Regarding the mention of "made by hackirby," I want to clarify that Skuld is entirely my creation. Any similarities or resemblances to other projects, including "Laze" (I saw you wrote some code on https://github.com/xKiian/Laze) are purely coincidental and not a result of skidding or copying. I was already coding Skuld before the release of "Laze": https://www.trellix.com/about/newsroom/stories/research/skuld-the-infostealer-that-speaks-golang/ (June 13, 2023).

Thank you for your understanding and cooperation.

Warm regards, hackirby

**Comment by hackirby** [comment]
But I appreciate your feedback, and you are right. I inadvertently overlooked adding some credits and I will ensure to add the appropriate credits to the original repositories. Thank you for bringing this to my attention.

**Comment by imvast** [comment]
ok nigga ur a joke

**Comment by hackirby** [comment]
Done. Thank you for bringing this to my attention. That's kind.
