### ISSUE TITLE
Allow to turn on/off Features  

### ISSUE THREAD

**Issue by UNKOWN1128** [hackirby/skuld#30]
Allow to turn on/off Features

**Comment by hackirby** [comment]
Simply edit `main.go` to remove the calls to the unwanted features.

**Comment by UNKOWN1128** [comment]
what about the bans my main account got perma suspended after using skuld idk why

**Comment by hackirby** [comment]
https://github.com/hackirby/skuld/issues/29

**Comment by UNKOWN1128** [comment]
ok got nothing out of there that is useful lmfao i'm using another stealer anyways but this one is really fucking good like great fucking job and i'm not glazing or dickriding this is actually the best one i've seen yet if i had some knowledge to make a Cryptor for .go i would add a gui and telegram webhook but anyways thanks for responding and great fucking job again best one i've seen yet

**Comment by hackirby** [comment]
thanks so much for the kind words! I'm really glad to hear that you find it useful and well-made. Best of luck with your projects.
