### ISSUE TITLE
Wallet Injection

### ISSUE THREAD

**Issue by undersessionin** [hackirby/skuld#35]
Hello,

I was trying to find the injection added on the Atomic wallet but i am unable to, i downloaded and unpacked it and searched everywhere and was not able to find it. ( Exodus Injection was there and easy to find but Atomic had a diff story )

I am creating this issue just for transparancy as i dont like running things that aren't open sourced and would like the check the injection code on the atomic wallet if that is okay. 

Can you please walk me through on where exacly can i find it after unpacking the app.asar file ?

Thank you and keep up the good work.

**Comment by hackirby** [comment]
Thank you for the compliments; I really appreciate them.

After extracting the ASAR file, you can find the atomic injection in `dist\electron\vendors.4e0fae9c1075cb883f42.js` at line 5732.
