### ISSUE TITLE
help me figure out the stealer

### ISSUE THREAD

**Issue by KARMAzm** [hackirby/skuld#38]
help me figure out the stealer, I entered git clone https://github.com/hackirby/skuld and cd skuld on the command line, but I can’t figure it out further, can someone help and explain how it works completely

**Comment by misapostle** [comment]
are you mentally ill????

it clearly says open main.go and edit the config, then run go build????

**Comment by KiExitDispatcher** [comment]
calm down lol, youre not "Im know it all" even though he cant follow simple instructions you dont have a reason to be rude lol

**Comment by hackirby** [comment]
Thank you for your contributions to this discussion. However, the conversation has become disrespectful, which is not in line with the supportive environment I aim to maintain. I am closing this thread now. Please remember to treat each other with respect and kindness in future discussions.
