### ISSUE TITLE
Please, remove this

### ISSUE THREAD

**Issue by aamaanaa** [hackirby/skuld#4]
i download a program from YouTube, and it got detected out by AV. did some analysis on the dropped exe, did some searching and came here. some skid took your program to hack people with it... 

it is also got featured on the hacker news so more and more idiots will be using this

**Comment by hackirby** [comment]
As mentioned in the disclaimer, I'm not responsible for any damages or legal consequences resulting from the use or misuse of this software. Rest assured, this grabber lacks any AV evasion technique, making it easily detectable. Idiots attempting to use it won't succeed.

**Comment by ghost** [comment]
i see,,, still on the news idiots use it, u can search for skuld on google.  indeed, the ani vm / debug lags behind, and the uac bypass alone is detected by defender and pretty mich all else

it wont suprise me to see poeple taking this and improve it and sell it on thier own, like they for example resselled phendrome stealer

**Comment by zephr1213** [comment]
skids are skids, they will always exist. private undetected stealers dont leak their methods. this project does, so its detectable.
