### ISSUE TITLE
Banning Discord

### ISSUE THREAD

**Issue by Techyh** [hackirby/skuld#41]
Pin this issue if you can.
if you consider using this **Malware**, please be careful when using a webhook, because you can get ### **banned forever** or for a couple of years from discord after using it.
what i suggest? make it work on telegram instead of discord.

**Comment by hackirby** [comment]
This issue is a duplicate of #29, but I agree that it's a good idea to pin it for visibility. I'm currently working on a new web panel to enhance our project's functionality and user experience. As a result, I will be discontinuing the use of Discord webhooks.
