### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mahdisbetter** [hackirby/skuld#44]
not a feature request or anything but i kinda think this whole project and the way this stealer works is generally kind of outdated and i was thinkin we could just rewrite it completely to instead be a small loader stub that tries its hardest to check for vms and evade heuristics / static analysis and then sideload a downloaded dll or binary that contains the actual malware

**Comment by hackirby** [comment]
The primary goal of this project is to demonstrate how a stealer works rather than to serve as a ready-to-use malware. A DLL/binary loader would go beyond the scope of this project.
