### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by DumbStackz4L** [hackirby/skuld#48]
So I ran this yesterday and it worked perfectly. But i deleted the server and I wanted to make a new exe so i re configured over and over again into the main go file and it didn't show anything. But it did show the fatal error but immediately exited the fake error. I also did make sure to check if I uninstalled the previous one and I did can you help me thanks.

**Comment by hackirby** [comment]
It sounds like the issue you're facing could be related to your antivirus software. If your antivirus program has learned to detect and block the executable, it might be automatically closing the program upon detecting it as a threat.
