### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by smthpy** [hackirby/skuld#5]
I've done this on Virtual Machines, with separate settings and environments of their own, yet I've seen one glaring problem.

Firefox seems to be the only browser that actually works regarding cookies. My guess, is, that the Chromium (and Chrome) have added their LDB file lock, which meant cookies wouldn't be grabbed if chrome was on.

But, even after chrome is killed, it does not grab anything. I'm sure their LDB lock fails once the browser itself is killed, so I'm guessing it's an issue with the code.

Given your grabber is quite damn good, I'd also imagine it'd attract a bit of attention. This may need urgent fixing, if the issue persists across multiple users.

**Comment by hackirby** [comment]
The issue with Chrome cookies path being incorrect has been resolved in the latest commit: https://github.com/hackirby/skuld/commit/cf71b743b0e6af86be8487d695fea81e9e88c241. Thank you a lot for reporting this huge mistake, and thank you for your kind words as well!
