### ISSUE TITLE
Yo bro i see your project is pretty cool but some features is missing like binary strip and obfuscation with xor !

### ISSUE THREAD

**Issue by furax124** [hackirby/skuld#7]
Maybe you can think of these features

**Comment by ghost** [comment]
it aint that hard to implement bro

**Comment by furax124** [comment]
> it aint that hard to implement bro

Pull a request then lol he want some suggestion lmao

**Comment by hackirby** [comment]
> Maybe you can think of these features

In fact, I have already developed a private obfuscator, and while I am considering releasing it, I haven't made a final decision yet.
Don't worry, if I decide to share it, I will provide the link to the obfuscator here.
But thank you for your suggestions and your kind words as well!
