### ISSUE TITLE
Add Mutex

### ISSUE THREAD

**Issue by chainski** [hackirby/skuld#8]
- [x] [Mutex](https://learn.microsoft.com/en-us/dotnet/api/system.threading.mutex?view=net-7.0) (single instance) to ensure that only one instance of the app is active at any given time.

### Advantages
- Thread-Safety
- Synchronization
- Prevention of Deadlocks
- Flexibility

**Comment by hackirby** [comment]
added in https://github.com/hackirby/skuld/commit/e42c262faae01ad9e48283a5fd7f495be4cb2be2
